---

- name: Build server certificate
  command: "{{ovpn_easyrsa}} build-server-full server nopass"
  args:
    creates: "{{ovpn_pkidir}}/private/server.key"

- name: Load service pool
  include_vars: "{{ item }}.yml"
  with_items: "{{ ovpn_services }}"

- name: Build service pool
  set_fact:
    ovpn_service_pool: "{{ ovpn_service_pool }} + ovpn_service_{{item}}"
  with_items: "{{ ovpn_services }}"

- name: Configure server
  template:
    src: server.conf.j2
    dest: "{{ovpn_etcdir}}/server.conf"
  notify: openvpn restart

- name: Enable OpenVPN server
  service:
    name: openvpn@server
    state: started
    enabled: yes
 