---

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Enable service
  firewalld:
    service: openvpn
    permanent: true
    state: enabled
  notify: firewald reload

- name: Enable masquerade
  firewalld:
    masquerade: yes
    permanent: true
    state: enabled
  notify: firewald reload
